/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.ide;

import com.robertkoszewski.dsl.ide.AbstractQuickUIIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QuickUIIdeModule extends AbstractQuickUIIdeModule {
}
