/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Boolean#isIsTrue <em>Is True</em>}</li>
 * </ul>
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends EObject
{
  /**
   * Returns the value of the '<em><b>Is True</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is True</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is True</em>' attribute.
   * @see #setIsTrue(boolean)
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getBoolean_IsTrue()
   * @model
   * @generated
   */
  boolean isIsTrue();

  /**
   * Sets the value of the '{@link com.robertkoszewski.dsl.quickUI.Boolean#isIsTrue <em>Is True</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is True</em>' attribute.
   * @see #isIsTrue()
   * @generated
   */
  void setIsTrue(boolean value);

} // Boolean
