/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checked</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Checked#getChecked <em>Checked</em>}</li>
 * </ul>
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getChecked()
 * @model
 * @generated
 */
public interface Checked extends Option, ConditionType
{
  /**
   * Returns the value of the '<em><b>Checked</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Checked</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Checked</em>' containment reference.
   * @see #setChecked(com.robertkoszewski.dsl.quickUI.Boolean)
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getChecked_Checked()
   * @model containment="true"
   * @generated
   */
  com.robertkoszewski.dsl.quickUI.Boolean getChecked();

  /**
   * Sets the value of the '{@link com.robertkoszewski.dsl.quickUI.Checked#getChecked <em>Checked</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Checked</em>' containment reference.
   * @see #getChecked()
   * @generated
   */
  void setChecked(com.robertkoszewski.dsl.quickUI.Boolean value);

} // Checked
