/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getConditionType()
 * @model
 * @generated
 */
public interface ConditionType extends EObject
{
} // ConditionType
