/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Empty</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getEmpty()
 * @model
 * @generated
 */
public interface Empty extends ConditionType
{
} // Empty
