/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends Option
{
} // Filter
