/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>On Click</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.OnClick#getCallback <em>Callback</em>}</li>
 * </ul>
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getOnClick()
 * @model
 * @generated
 */
public interface OnClick extends Option
{
  /**
   * Returns the value of the '<em><b>Callback</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Callback</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Callback</em>' attribute.
   * @see #setCallback(String)
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getOnClick_Callback()
   * @model
   * @generated
   */
  String getCallback();

  /**
   * Sets the value of the '{@link com.robertkoszewski.dsl.quickUI.OnClick#getCallback <em>Callback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Callback</em>' attribute.
   * @see #getCallback()
   * @generated
   */
  void setCallback(String value);

} // OnClick
