/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.robertkoszewski.dsl.quickUI.QuickUIFactory
 * @model kind="package"
 * @generated
 */
public interface QuickUIPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "quickUI";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.robertkoszewski.com/dsl/QuickUI";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "quickUI";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QuickUIPackage eINSTANCE = com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl.init();

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.UIModelImpl <em>UI Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.UIModelImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getUIModel()
   * @generated
   */
  int UI_MODEL = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL__ALIAS = 0;

  /**
   * The feature id for the '<em><b>Window</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL__WINDOW = 1;

  /**
   * The number of structural features of the '<em>UI Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.AliasImpl <em>Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.AliasImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getAlias()
   * @generated
   */
  int ALIAS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS__NAME = 0;

  /**
   * The feature id for the '<em><b>Package</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS__PACKAGE = 1;

  /**
   * The number of structural features of the '<em>Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.PackageImpl <em>Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.PackageImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getPackage()
   * @generated
   */
  int PACKAGE = 2;

  /**
   * The feature id for the '<em><b>Pname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__PNAME = 0;

  /**
   * The feature id for the '<em><b>Subp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__SUBP = 1;

  /**
   * The number of structural features of the '<em>Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.WindowImpl <em>Window</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.WindowImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getWindow()
   * @generated
   */
  int WINDOW = 3;

  /**
   * The feature id for the '<em><b>Main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__MAIN = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__NAME = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__TITLE = 2;

  /**
   * The feature id for the '<em><b>Menu elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__MENU_ELEMENTS = 3;

  /**
   * The feature id for the '<em><b>Content elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__CONTENT_ELEMENTS = 4;

  /**
   * The number of structural features of the '<em>Window</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.ElementImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Subelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__SUBELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.JavaElementImpl <em>Java Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.JavaElementImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getJavaElement()
   * @generated
   */
  int JAVA_ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Subelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ELEMENT__SUBELEMENT = ELEMENT__SUBELEMENT;

  /**
   * The feature id for the '<em><b>Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ELEMENT__ALIAS = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Java Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.RowImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getRow()
   * @generated
   */
  int ROW = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Subelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__SUBELEMENT = ELEMENT__SUBELEMENT;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.OptionImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getOption()
   * @generated
   */
  int OPTION = 7;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.LabelImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__VALUE = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.EnabledImpl <em>Enabled</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.EnabledImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getEnabled()
   * @generated
   */
  int ENABLED = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENABLED__CONDITION = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enabled</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENABLED_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.ConditionImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 10;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Negation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NEGATION = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 2;

  /**
   * The feature id for the '<em><b>Subcondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__SUBCONDITION = 3;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.ConditionTypeImpl <em>Condition Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.ConditionTypeImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getConditionType()
   * @generated
   */
  int CONDITION_TYPE = 11;

  /**
   * The number of structural features of the '<em>Condition Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.CheckedImpl <em>Checked</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.CheckedImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getChecked()
   * @generated
   */
  int CHECKED = 12;

  /**
   * The feature id for the '<em><b>Checked</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKED__CHECKED = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Checked</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKED_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.OnClickImpl <em>On Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.OnClickImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getOnClick()
   * @generated
   */
  int ON_CLICK = 13;

  /**
   * The feature id for the '<em><b>Callback</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_CLICK__CALLBACK = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>On Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_CLICK_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.BooleanImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 14;

  /**
   * The feature id for the '<em><b>Is True</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__IS_TRUE = 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.FilterImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 15;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = OPTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.robertkoszewski.dsl.quickUI.impl.EmptyImpl <em>Empty</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robertkoszewski.dsl.quickUI.impl.EmptyImpl
   * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getEmpty()
   * @generated
   */
  int EMPTY = 16;

  /**
   * The number of structural features of the '<em>Empty</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPTY_FEATURE_COUNT = CONDITION_TYPE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.UIModel <em>UI Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>UI Model</em>'.
   * @see com.robertkoszewski.dsl.quickUI.UIModel
   * @generated
   */
  EClass getUIModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.robertkoszewski.dsl.quickUI.UIModel#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alias</em>'.
   * @see com.robertkoszewski.dsl.quickUI.UIModel#getAlias()
   * @see #getUIModel()
   * @generated
   */
  EReference getUIModel_Alias();

  /**
   * Returns the meta object for the containment reference list '{@link com.robertkoszewski.dsl.quickUI.UIModel#getWindow <em>Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Window</em>'.
   * @see com.robertkoszewski.dsl.quickUI.UIModel#getWindow()
   * @see #getUIModel()
   * @generated
   */
  EReference getUIModel_Window();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Alias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alias</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Alias
   * @generated
   */
  EClass getAlias();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Alias#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Alias#getName()
   * @see #getAlias()
   * @generated
   */
  EAttribute getAlias_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.robertkoszewski.dsl.quickUI.Alias#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Package</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Alias#getPackage()
   * @see #getAlias()
   * @generated
   */
  EReference getAlias_Package();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Package <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Package
   * @generated
   */
  EClass getPackage();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Package#getPname <em>Pname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pname</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Package#getPname()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Pname();

  /**
   * Returns the meta object for the containment reference '{@link com.robertkoszewski.dsl.quickUI.Package#getSubp <em>Subp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subp</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Package#getSubp()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_Subp();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Window <em>Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Window</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Window
   * @generated
   */
  EClass getWindow();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Window#isMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Main</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Window#isMain()
   * @see #getWindow()
   * @generated
   */
  EAttribute getWindow_Main();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Window#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Window#getName()
   * @see #getWindow()
   * @generated
   */
  EAttribute getWindow_Name();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Window#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Window#getTitle()
   * @see #getWindow()
   * @generated
   */
  EAttribute getWindow_Title();

  /**
   * Returns the meta object for the containment reference list '{@link com.robertkoszewski.dsl.quickUI.Window#getMenu_elements <em>Menu elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Menu elements</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Window#getMenu_elements()
   * @see #getWindow()
   * @generated
   */
  EReference getWindow_Menu_elements();

  /**
   * Returns the meta object for the containment reference list '{@link com.robertkoszewski.dsl.quickUI.Window#getContent_elements <em>Content elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Content elements</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Window#getContent_elements()
   * @see #getWindow()
   * @generated
   */
  EReference getWindow_Content_elements();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.robertkoszewski.dsl.quickUI.Element#getSubelement <em>Subelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subelement</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Element#getSubelement()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Subelement();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.JavaElement <em>Java Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Java Element</em>'.
   * @see com.robertkoszewski.dsl.quickUI.JavaElement
   * @generated
   */
  EClass getJavaElement();

  /**
   * Returns the meta object for the reference '{@link com.robertkoszewski.dsl.quickUI.JavaElement#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Alias</em>'.
   * @see com.robertkoszewski.dsl.quickUI.JavaElement#getAlias()
   * @see #getJavaElement()
   * @generated
   */
  EReference getJavaElement_Alias();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Label#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Label#getValue()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Value();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Enabled <em>Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enabled</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Enabled
   * @generated
   */
  EClass getEnabled();

  /**
   * Returns the meta object for the containment reference '{@link com.robertkoszewski.dsl.quickUI.Enabled#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Enabled#getCondition()
   * @see #getEnabled()
   * @generated
   */
  EReference getEnabled_Condition();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the reference '{@link com.robertkoszewski.dsl.quickUI.Condition#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Condition#getElement()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Element();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Condition#isNegation <em>Negation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negation</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Condition#isNegation()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Negation();

  /**
   * Returns the meta object for the containment reference '{@link com.robertkoszewski.dsl.quickUI.Condition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Condition#getCondition()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Condition();

  /**
   * Returns the meta object for the containment reference '{@link com.robertkoszewski.dsl.quickUI.Condition#getSubcondition <em>Subcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subcondition</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Condition#getSubcondition()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Subcondition();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.ConditionType <em>Condition Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition Type</em>'.
   * @see com.robertkoszewski.dsl.quickUI.ConditionType
   * @generated
   */
  EClass getConditionType();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Checked <em>Checked</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checked</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Checked
   * @generated
   */
  EClass getChecked();

  /**
   * Returns the meta object for the containment reference '{@link com.robertkoszewski.dsl.quickUI.Checked#getChecked <em>Checked</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Checked</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Checked#getChecked()
   * @see #getChecked()
   * @generated
   */
  EReference getChecked_Checked();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.OnClick <em>On Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>On Click</em>'.
   * @see com.robertkoszewski.dsl.quickUI.OnClick
   * @generated
   */
  EClass getOnClick();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.OnClick#getCallback <em>Callback</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Callback</em>'.
   * @see com.robertkoszewski.dsl.quickUI.OnClick#getCallback()
   * @see #getOnClick()
   * @generated
   */
  EAttribute getOnClick_Callback();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link com.robertkoszewski.dsl.quickUI.Boolean#isIsTrue <em>Is True</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is True</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Boolean#isIsTrue()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_IsTrue();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for class '{@link com.robertkoszewski.dsl.quickUI.Empty <em>Empty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Empty</em>'.
   * @see com.robertkoszewski.dsl.quickUI.Empty
   * @generated
   */
  EClass getEmpty();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QuickUIFactory getQuickUIFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.UIModelImpl <em>UI Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.UIModelImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getUIModel()
     * @generated
     */
    EClass UI_MODEL = eINSTANCE.getUIModel();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UI_MODEL__ALIAS = eINSTANCE.getUIModel_Alias();

    /**
     * The meta object literal for the '<em><b>Window</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UI_MODEL__WINDOW = eINSTANCE.getUIModel_Window();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.AliasImpl <em>Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.AliasImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getAlias()
     * @generated
     */
    EClass ALIAS = eINSTANCE.getAlias();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALIAS__NAME = eINSTANCE.getAlias_Name();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALIAS__PACKAGE = eINSTANCE.getAlias_Package();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.PackageImpl <em>Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.PackageImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getPackage()
     * @generated
     */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
     * The meta object literal for the '<em><b>Pname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__PNAME = eINSTANCE.getPackage_Pname();

    /**
     * The meta object literal for the '<em><b>Subp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__SUBP = eINSTANCE.getPackage_Subp();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.WindowImpl <em>Window</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.WindowImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getWindow()
     * @generated
     */
    EClass WINDOW = eINSTANCE.getWindow();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WINDOW__MAIN = eINSTANCE.getWindow_Main();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WINDOW__NAME = eINSTANCE.getWindow_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WINDOW__TITLE = eINSTANCE.getWindow_Title();

    /**
     * The meta object literal for the '<em><b>Menu elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW__MENU_ELEMENTS = eINSTANCE.getWindow_Menu_elements();

    /**
     * The meta object literal for the '<em><b>Content elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW__CONTENT_ELEMENTS = eINSTANCE.getWindow_Content_elements();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.ElementImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '<em><b>Subelement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__SUBELEMENT = eINSTANCE.getElement_Subelement();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.JavaElementImpl <em>Java Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.JavaElementImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getJavaElement()
     * @generated
     */
    EClass JAVA_ELEMENT = eINSTANCE.getJavaElement();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JAVA_ELEMENT__ALIAS = eINSTANCE.getJavaElement_Alias();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.RowImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.OptionImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.LabelImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__VALUE = eINSTANCE.getLabel_Value();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.EnabledImpl <em>Enabled</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.EnabledImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getEnabled()
     * @generated
     */
    EClass ENABLED = eINSTANCE.getEnabled();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENABLED__CONDITION = eINSTANCE.getEnabled_Condition();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.ConditionImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__ELEMENT = eINSTANCE.getCondition_Element();

    /**
     * The meta object literal for the '<em><b>Negation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NEGATION = eINSTANCE.getCondition_Negation();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '<em><b>Subcondition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__SUBCONDITION = eINSTANCE.getCondition_Subcondition();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.ConditionTypeImpl <em>Condition Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.ConditionTypeImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getConditionType()
     * @generated
     */
    EClass CONDITION_TYPE = eINSTANCE.getConditionType();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.CheckedImpl <em>Checked</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.CheckedImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getChecked()
     * @generated
     */
    EClass CHECKED = eINSTANCE.getChecked();

    /**
     * The meta object literal for the '<em><b>Checked</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKED__CHECKED = eINSTANCE.getChecked_Checked();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.OnClickImpl <em>On Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.OnClickImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getOnClick()
     * @generated
     */
    EClass ON_CLICK = eINSTANCE.getOnClick();

    /**
     * The meta object literal for the '<em><b>Callback</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ON_CLICK__CALLBACK = eINSTANCE.getOnClick_Callback();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.BooleanImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Is True</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__IS_TRUE = eINSTANCE.getBoolean_IsTrue();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.FilterImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '{@link com.robertkoszewski.dsl.quickUI.impl.EmptyImpl <em>Empty</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robertkoszewski.dsl.quickUI.impl.EmptyImpl
     * @see com.robertkoszewski.dsl.quickUI.impl.QuickUIPackageImpl#getEmpty()
     * @generated
     */
    EClass EMPTY = eINSTANCE.getEmpty();

  }

} //QuickUIPackage
