/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UI Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.UIModel#getAlias <em>Alias</em>}</li>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.UIModel#getWindow <em>Window</em>}</li>
 * </ul>
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getUIModel()
 * @model
 * @generated
 */
public interface UIModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference list.
   * The list contents are of type {@link com.robertkoszewski.dsl.quickUI.Alias}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference list.
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getUIModel_Alias()
   * @model containment="true"
   * @generated
   */
  EList<Alias> getAlias();

  /**
   * Returns the value of the '<em><b>Window</b></em>' containment reference list.
   * The list contents are of type {@link com.robertkoszewski.dsl.quickUI.Window}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Window</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Window</em>' containment reference list.
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getUIModel_Window()
   * @model containment="true"
   * @generated
   */
  EList<Window> getWindow();

} // UIModel
