/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Window</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Window#isMain <em>Main</em>}</li>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Window#getName <em>Name</em>}</li>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Window#getTitle <em>Title</em>}</li>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Window#getMenu_elements <em>Menu elements</em>}</li>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.Window#getContent_elements <em>Content elements</em>}</li>
 * </ul>
 *
 * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getWindow()
 * @model
 * @generated
 */
public interface Window extends EObject
{
  /**
   * Returns the value of the '<em><b>Main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' attribute.
   * @see #setMain(boolean)
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getWindow_Main()
   * @model
   * @generated
   */
  boolean isMain();

  /**
   * Sets the value of the '{@link com.robertkoszewski.dsl.quickUI.Window#isMain <em>Main</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' attribute.
   * @see #isMain()
   * @generated
   */
  void setMain(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getWindow_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.robertkoszewski.dsl.quickUI.Window#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getWindow_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link com.robertkoszewski.dsl.quickUI.Window#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Menu elements</b></em>' containment reference list.
   * The list contents are of type {@link com.robertkoszewski.dsl.quickUI.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menu elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menu elements</em>' containment reference list.
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getWindow_Menu_elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getMenu_elements();

  /**
   * Returns the value of the '<em><b>Content elements</b></em>' containment reference list.
   * The list contents are of type {@link com.robertkoszewski.dsl.quickUI.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content elements</em>' containment reference list.
   * @see com.robertkoszewski.dsl.quickUI.QuickUIPackage#getWindow_Content_elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getContent_elements();

} // Window
