/**
 * generated by Xtext 2.10.0
 */
package com.robertkoszewski.dsl.ui.contentassist;

import com.robertkoszewski.dsl.ui.contentassist.AbstractQuickUIProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QuickUIProposalProvider extends AbstractQuickUIProposalProvider {
}
