/*
 * generated by Xtext 2.10.0
 */
package com.robertkoszewski.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class QuickUIRuntimeModule extends AbstractQuickUIRuntimeModule {
}
