/**
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.quickUI.impl;

import com.robertkoszewski.dsl.quickUI.QuickUIPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Package</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.impl.PackageImpl#getPname <em>Pname</em>}</li>
 *   <li>{@link com.robertkoszewski.dsl.quickUI.impl.PackageImpl#getSubp <em>Subp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PackageImpl extends MinimalEObjectImpl.Container implements com.robertkoszewski.dsl.quickUI.Package
{
  /**
   * The default value of the '{@link #getPname() <em>Pname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPname()
   * @generated
   * @ordered
   */
  protected static final String PNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPname() <em>Pname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPname()
   * @generated
   * @ordered
   */
  protected String pname = PNAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSubp() <em>Subp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubp()
   * @generated
   * @ordered
   */
  protected com.robertkoszewski.dsl.quickUI.Package subp;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PackageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuickUIPackage.Literals.PACKAGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPname()
  {
    return pname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPname(String newPname)
  {
    String oldPname = pname;
    pname = newPname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuickUIPackage.PACKAGE__PNAME, oldPname, pname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public com.robertkoszewski.dsl.quickUI.Package getSubp()
  {
    return subp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubp(com.robertkoszewski.dsl.quickUI.Package newSubp, NotificationChain msgs)
  {
    com.robertkoszewski.dsl.quickUI.Package oldSubp = subp;
    subp = newSubp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QuickUIPackage.PACKAGE__SUBP, oldSubp, newSubp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSubp(com.robertkoszewski.dsl.quickUI.Package newSubp)
  {
    if (newSubp != subp)
    {
      NotificationChain msgs = null;
      if (subp != null)
        msgs = ((InternalEObject)subp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QuickUIPackage.PACKAGE__SUBP, null, msgs);
      if (newSubp != null)
        msgs = ((InternalEObject)newSubp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QuickUIPackage.PACKAGE__SUBP, null, msgs);
      msgs = basicSetSubp(newSubp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuickUIPackage.PACKAGE__SUBP, newSubp, newSubp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QuickUIPackage.PACKAGE__SUBP:
        return basicSetSubp(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QuickUIPackage.PACKAGE__PNAME:
        return getPname();
      case QuickUIPackage.PACKAGE__SUBP:
        return getSubp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QuickUIPackage.PACKAGE__PNAME:
        setPname((String)newValue);
        return;
      case QuickUIPackage.PACKAGE__SUBP:
        setSubp((com.robertkoszewski.dsl.quickUI.Package)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QuickUIPackage.PACKAGE__PNAME:
        setPname(PNAME_EDEFAULT);
        return;
      case QuickUIPackage.PACKAGE__SUBP:
        setSubp((com.robertkoszewski.dsl.quickUI.Package)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QuickUIPackage.PACKAGE__PNAME:
        return PNAME_EDEFAULT == null ? pname != null : !PNAME_EDEFAULT.equals(pname);
      case QuickUIPackage.PACKAGE__SUBP:
        return subp != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (pname: ");
    result.append(pname);
    result.append(')');
    return result.toString();
  }

} //PackageImpl
