/*
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.parser.antlr;

import com.google.inject.Inject;
import com.robertkoszewski.dsl.parser.antlr.internal.InternalQuickUIParser;
import com.robertkoszewski.dsl.services.QuickUIGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class QuickUIParser extends AbstractAntlrParser {

	@Inject
	private QuickUIGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQuickUIParser createParser(XtextTokenStream stream) {
		return new InternalQuickUIParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "UIModel";
	}

	public QuickUIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QuickUIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
