/*
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QuickUIAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/robertkoszewski/dsl/parser/antlr/internal/InternalQuickUI.tokens");
	}
}
