/**
 * generated by Xtext 2.10.0
 */
package com.robertkoszewski.dsl.validation;

import com.robertkoszewski.dsl.validation.AbstractQuickUIValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class QuickUIValidator extends AbstractQuickUIValidator {
}
