/**
 * generated by Xtext 2.10.0
 */
package com.robertkoszewski.dsl;

import com.robertkoszewski.dsl.QuickUIStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class QuickUIStandaloneSetup extends QuickUIStandaloneSetupGenerated {
  public static void doSetup() {
    new QuickUIStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
