/*
 * generated by Xtext 2.11.0
 */
package com.robertkoszewski.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQuickUIScopeProvider extends DelegatingScopeProvider {
}
