/**
 * generated by Xtext 2.10.0
 */
package com.robertkoszewski.dsl.ui;

import com.robertkoszewski.dsl.ui.AbstractQuickUIUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QuickUIUiModule extends AbstractQuickUIUiModule {
  public QuickUIUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
